authors = ["Peter Ahrens <ptrahrens@gmail.com>"]
name = "Hyperspecialize"
uuid = "39c0bb8c-69c9-11e8-0cb2-fdbfca5dda29"
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
